blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://t3.gg/discord
    about: Join the Discord server and ask community members for help about anything related to Uploadthing